### ISSUE TITLE
大佬做的真不错

### ISSUE THREAD

**Issue by Block2B** [andandroidor/ourtv#11]
唯一一款下到电视上直接可以看的，希望可以支持下去，天气太热，请你喝杯可乐，谢谢为老年人解决问题，音量按键也会调出频道选择或许可以关掉。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by andandroidor** [comment]
收到 感谢反馈

**Comment by andandroidor** [comment]
请用新版本再试试 是否还存在问题
