### ISSUE TITLE
在OPPO手机上出现bug

### ISSUE THREAD

**Issue by fuxinyi0505** [andandroidor/ourtv#15]
机型：OPPO ACE2
系统：Android 13
问题：手机版界面无论点哪个频道都会闪退，重新点击app，进入应用后播放的是闪退前点击的频道。

https://github.com/user-attachments/assets/5c7bebb7-4c8f-4ac2-9236-4f88d980a14d

**Comment by andandroidor** [comment]
收到，感谢反馈

**Comment by andandroidor** [comment]
请用新版再试试

**Comment by xxjxue** [comment]
能不能把3.0.2安装软件放上来，这个不会有楼上反应的情况，我也是升级最新版本出现这个情况，谢谢版主。
