### ISSUE TITLE
换台方式希望优化，可以方便老人使用

### ISSUE THREAD

**Issue by ddwty** [andandroidor/ourtv#16]
感谢作者🙏直播很清晰流畅，换台速度也快，但家里的老人更习惯一直按“上”或“下”这样的方式换台。

现在我们需要先呼出菜单，然后按“上下左右”找到想要的电视台，然后再按“OK”键，老人需要看一下电视屏幕，再低头看一下遥控器，再抬头看电视屏幕.......如果手速慢了几秒，选台界面就消失了，又需要从头开始操作，一直没有换台成功。

希望能够在交互上，有一个便于老人使用的设计，按“上”或“下”就能轮流换台；在选台菜单页面，每个电视台按钮的背景调成纯色，提高文字对比度；适当增加选台界面自动消失的时间。

**Comment by andandroidor** [comment]
收到 感谢反馈

**Comment by andandroidor** [comment]
已优化频道名称UI显示   延长选台界面到15秒
暂不支持上下换台

**Comment by ddwty** [comment]
> 已优化频道名称UI显示 延长选台界面到15秒 暂不支持上下换台

感谢作者～更新好迅速😯
