### ISSUE TITLE
能不能添加数字按键换台的功能

### ISSUE THREAD

**Issue by Ba1ker** [andandroidor/ourtv#17]
mytv新版本一直闪退，在mytv的issue看到了ourtv的仓库地址就下载来看看会不会闪退。。。托作者的福，现在已经看上电视了就是长辈对ourtv换台的方式还不太习惯，而且摁数字换不了台，请问作者能不能把频道图标和标题改得大一点呢，或者改成左侧列表大图标大字体的形式方便长辈看清转台

**Comment by andandroidor** [comment]
啊？还小啊，已经改了好几次了😂

**Comment by andandroidor** [comment]
抱歉，无计划支持数字换台，没有理由这么做
