### ISSUE TITLE
CCTV和CNTN各个台的文字描述「频道」似乎显得多余和累赘了？一整版的「频道」看得人眼花，可否減去「频道」二字？谢谢。

### ISSUE THREAD

**Issue by javadodobird** [andandroidor/ourtv#18]
CCTV和CNTN各个台的文字描述「频道」似乎显得多余和累赘了？一整版的「频道」看得人眼花，可否減去「频道」二字？谢谢。

**Comment by andandroidor** [comment]
见  #9 issue  可以去掉

**Comment by javadodobird** [comment]
文字敘述请保留，就是每个台后面的「频道」两个字多余了，一整屏的「频道」密密麻麻的看着眼花，例如「CCTV 1综合频道」就写「CCTV-1综合」就可以了简洁，谢谢了。

**Comment by andandroidor** [comment]
见3.0.6
