### ISSUE TITLE
安卓5可以支持吗？

### ISSUE THREAD

**Issue by alcatraz-zz** [andandroidor/ourtv#2]
你好，这支持最低安卓8版本。小米电视/盒子大部分是安卓5。下个更新可以支持吗？谢谢

**Comment by andandroidor** [comment]
新版本已降低到19  支持android4.4 但未经测试。

**Comment by dxxjg** [comment]
> 新版本已降低到19 支持android4.4 但未经测试。

请问是否有计划再降一下至4.3（18）

**Comment by andandroidor** [comment]
不可以了 播放器内核最低到19

**Comment by dxxjg** [comment]
> 不可以了 播放器内核最低到19

明白了，谢谢！

**Comment by sobergou** [comment]
> 不可以了 播放器内核最低到19

大佬之前深度维护了my-tv的央视频web方案，我看你伪装的是安卓方案，web方案，我们之前也是对抗密钥解析，最后web方案将加密植入视频流中，web用的视频解码器是hls.js，安卓用的是Media3、ffmpeg，我们没有继续跟进，对抗解密太累了；这个属于原生源，全球播放不卡顿，不懂得人，因不能看了，还抱怨骂两句，心寒，后期也没公开发版，小范围发版；你用的方案是我计划做没有做的，央视频安卓方案目前还没在视频流上加密，如果你这边用户量上来，估计也会动态改key，或者直接参考web方案，将加密做到视频流中，在解码器中动态解析。
