### ISSUE TITLE
希望获取3.0.2手机版本安装文件

### ISSUE THREAD

**Issue by xxjxue** [andandroidor/ourtv#20]
更新文件到3.0.5无法换台，换台会闪退，希望提供3.0.2手机版安装文件。

**Comment by andandroidor** [comment]
能否录个视频  看看 
机型、系统是什么

**Comment by andandroidor** [comment]
用新版本试试 旧版本安装包已删除 没有备份🤕

**Comment by xxjxue** [comment]
![IMG_20240811_154307](https://github.com/user-attachments/assets/d6c0034d-7b2d-4e7e-a32d-ef3d99581053)

https://github.com/user-attachments/assets/90be707a-a6cc-4e51-819f-89339c520553

**Comment by xxjxue** [comment]
![Uploading IMG_20240811_154307.jpg…]()

**Comment by andandroidor** [comment]
收到，感谢回复，我也升级下手机系统试试
