### ISSUE TITLE
使用OUR-TV 3.1.0后的关于频道节目的几个建议。

### ISSUE THREAD

**Issue by ebaogogo** [andandroidor/ourtv#23]
1、是否可以频道列表提供节目提示（比如天津台正在播放什么节目）；可参考小薇直播的节目形式；
2、是否可以直接上下切换频道，而不是必须返回到总目录去一直盲按。
3、是否可以增加央视3/6/8，并做一个从低到高的排序；

**Comment by ebaogogo** [comment]
另外个人建议是否可以自动升级推送，不然github.com经常国内无法连接，更新不及时；

**Comment by andandroidor** [comment]
> 1、是否可以频道列表提供节目提示（比如天津台正在播放什么节目）；可参考小薇直播的节目形式； 2、是否可以直接上下切换频道，而不是必须返回到总目录去一直盲按。 3、是否可以增加央视3/6/8，并做一个从低到高的排序；

感谢您热心反馈 
1. 节目预告 参考手机版 实际是有的 只是tv版没有合适的地方展示出来
2. 暂无计划实现上下切换，上下切换本身就是盲按
3. 不能，想知道为什么，可以TG联系我
4. 恕我不能，TG群里会有最新版本推送
5. 频道排序功能在计划中，敬请期待

感谢支持

**Comment by ebaogogo** [comment]
Telegram是被严格管制的软件，就像X，或Facebook一样，搞这些群对国内的人都是障碍的；弄个钉钉或微信群甚至QQ群更加实际一些；毕竟我们开发的产品用户还是在国内，如果脱离了群众是很难成功的；

**Comment by ebaogogo** [comment]
我这里经常无法访问GITHUB,只能通过修改hosts文件访问：

# GitHub Start
20.205.243.166 github.com
20.205.243.166 gist.github.com
20.205.243.166 assets-cdn.github.com
20.205.243.166 raw.githubusercontent.com
20.205.243.166 git.githubusercontent.com
20.205.243.166 cloud.githubusercontent.com
20.205.243.166 camo.githubusercontent.com
20.205.243.166 avatars0.githubusercontent.com
20.205.243.166 avatars1.githubusercontent.com
20.205.243.166 avatars2.githubusercontent.com
20.205.243.166 avatars3.githubusercontent.com
20.205.243.166 avatars4.githubusercontent.com
20.205.243.166 avatars5.githubusercontent.com
20.205.243.166 avatars6.githubusercontent.com
20.205.243.166 avatars7.githubusercontent.com
20.205.243.166 avatars8.githubusercontent.com

151.101.129.194 github.global.ssl.fastly.net

# GitHub End

**Comment by andandroidor** [comment]
您可能不知道  国内电视类的app  需要资质才可以啊
钉钉或微信群甚至QQ群更容易被封

**Comment by ebaogogo** [comment]
感谢你辛苦的努力，理解你说的，

**Comment by ebaogogo** [comment]
感谢你辛苦的努力，以及耐心的回答。
1、虽然钉钉或微信群甚至QQ群更容易被封，但是总比TG完全无法访问要好啊。用户想反馈问题都无法联系，就比如现在这个github.com，很多人就无法访问，是一些热心的用户，转发到微信、QQ、钉钉后，才传播出去的；群里可叫人帮忙管理，不谈敏感问题，只回答用户反馈问题就OK了。
2、当然知道国内电视需要资质，电视家被封就是这样的例子，之前作者疲惫应付反复解密源也是因为反复被封导致；所以才想办法解决这些问题，比如自动升级推送 ，比如空壳播放器+换源，比如网页模式，想一个APP适应所有的盒子和所有的网络线路不现实，想一下兼容所有的手机和电视甚至车载也不现实，要么就区分版本，要么就有所取舍，要么就使用AI等来尽量学习环境适应。一旦产品出名了，成商业了，肯定会被关注了，那就换个样子和场景出现；
