### ISSUE TITLE
闪退问题严重

### ISSUE THREAD

**Issue by codyyuan413** [andandroidor/ourtv#24]
小米10S手机 andorid 13，安装后切换频道就闪退。还有tv版本 打开后点击频道就闪退呢。麻烦修复一下。以前mytv确实没遇到过闪退问题。 多谢了。

**Comment by andandroidor** [comment]
感谢反馈

**Comment by slasjh** [comment]
手机版一换台就闪退，red mi K40S

**Comment by andandroidor** [comment]
> 手机版一换台就闪退，red mi K40S

在Android13上没能复现      请问下你的Android系统版本是多少？

**Comment by codyyuan413** [comment]
图片你看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月14日(周三) 下午3:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [andandroidor/ourtv] 闪退问题严重 (Issue #24)




  
手机版一换台就闪退，red mi K40S
  
在Android13上没能复现      请问下你的Android系统版本是多少？

**Comment by andandroidor** [comment]
已修正 由性能监控工具sentrySDK引起，该sdk 调用  pthread_getcpuclockid  时引发了部分机型上崩溃

**Comment by slasjh** [comment]
> > 手机版一换台就闪退，red mi K40S
> 
> 在Android13上没能复现 请问下你的Android系统版本是多少？

Android13     miui14.0.9
