### ISSUE TITLE
电视版的操作逻辑可以改一下吗？没办法上下按键换台

### ISSUE THREAD

**Issue by Lsi77** [andandroidor/ourtv#26]

**Comment by andandroidor** [comment]
见 https://github.com/andandroidor/ourtv/issues?q=is%3Aissue+is%3Aclosed+%E4%B8%8A%E4%B8%8B

**Comment by andandroidor** [comment]
抱歉 暂无计划支持 上下切换

**Comment by andandroidor** [comment]
OurTV电视版3.2.8版本隐藏技能：

援助任意金额：
可永久开启部分频道的回看功能
和
去除护眼提醒里面的二维码；

累计援助开发者超过99元：
3年内，
可开启遥控器上下键（或频道+-键）换台 
和 
可禁用护眼提醒。

不喜勿喷，感谢支持。
