### ISSUE TITLE
TV端无法切换清晰度

### ISSUE THREAD

**Issue by feeeei** [andandroidor/ourtv#3]
首先感谢作者

在TV端，按菜单弹出的清晰度列表，按上下左右都无法切换，只能默认好像是比较低的清晰度

**Comment by andandroidor** [comment]
> 首先感谢作者
> 
> 在TV端，按菜单弹出的清晰度列表，按上下左右都无法切换，只能默认好像是比较低的清晰度

感谢反馈，已修正，请用最新版本3.0.1试试

**Comment by Tlonglan** [comment]
> > 首先感谢作者
> > 在TV端，按菜单弹出的清晰度列表，按上下左右都无法切换，只能默认好像是比较低的清晰度
> 
> 感谢反馈，已修正，请用最新版本3.0.1试试

小米电视上最新的 3.0.5 好像又切换不了清晰度了

**Comment by andandroidor** [comment]
收到，感谢反馈

**Comment by andandroidor** [comment]
这块的逻辑没动过 用3.0.6试试呢

**Comment by Tlonglan** [comment]
> 这块的逻辑没动过 用3.0.6试试呢
enen~ 刚才试了一下3.0.6，发现是在选择的时候 在电视上那个圈圈不太显眼，就以为没有跳转到其他清晰度，原来不是马上切换的 :joy: ，建议可以优化一下选择的样式~

谢谢大佬开发这款软件！ :heart:
