### ISSUE TITLE
使用ourtv的几点体验

### ISSUE THREAD

**Issue by taddyboy** [andandroidor/ourtv#35]
本人在海信智能电视上使用ourtv的几点体验：
首先软件响应度还是很好的，换台很快，几乎是秒换，这点给大神点个大赞！下面几个问题希望作者慢慢提升，使软件越来越好。
1、分辨率和画面：就是调成高分辨率的，实际图像清晰度没有太多提升，画面始终发白，有一种毛玻璃既视感，不知道是怎么回事，还有，希望作者在用户调分辨率时，如果设置为1080P,就让所有节目都跟着调成1080P,而不是一个台一个台的调分辨率，来回换频道时，就又自动改成默认的分辨率了。
2、希望作者改成电视遥控器导航上下键能够换频道功能，增加反转功能，这样能够方便90%以上的用户收视习惯。
3、频道列表可以进一步优化，方便用户查看。
4、希望增加一些港台或海外电影电视剧频道，增强娱乐性
感谢作者的辛勤劳动，愿软件越做越好，超越曾经的mytv

**Comment by andandroidor** [comment]
感谢反馈
1. 分辨率一台一换是最近的特意改动，见更新日志，见谅
2. 换台方式的修改正在计划中
3. 这个的确需要再改进，目前优先级可以往后放放
4. 以稳定源为基础，其他第三方源暂无计划增加
