### ISSUE TITLE
安装后打开软件，电视提示“很抱歉，‘TV’已停止运行”

### ISSUE THREAD

**Issue by zdbss** [andandroidor/ourtv#37]
TCL电视，安卓4.4.3系统。
安装后打开软件，电视提示“很抱歉，‘TV’已停止运行”，希望可以优化一下，必要时本人可协助测试。

**Comment by andandroidor** [comment]
抱歉   低版本兼容性不是很好

**Comment by 1Boom** [comment]
> 抱歉 低版本兼容性不是很好

同问题，安卓4.0的电视，求匹配…

**Comment by andandroidor** [comment]
> > 抱歉 低版本兼容性不是很好
> 
> 同问题，安卓4.0的电视，求匹配…

历史的车轮滚滚向前，非我所能抵抗😁早日淘汰旧机器
