### ISSUE TITLE
默认音量有点大，每次转台都需要重新调节。

### ISSUE THREAD

**Issue by seven4lucky** [andandroidor/ourtv#38]
您好，请问每次转台都需要重新调节音量，是否可以增加一个设置调节？或者默认音量调低一些？感谢您的分享。

**Comment by andandroidor** [comment]
收到，感谢反馈， 因为近期部分电视机型系统的逻辑调整 导致无法接收音量按键的回调。新版本3.2.6已适配修复，敬请期待。
