### ISSUE TITLE
能否添加上下键换台功能？

### ISSUE THREAD

**Issue by nssiwi** [andandroidor/ourtv#40]

**Comment by andandroidor** [comment]
正在开发中，敬请期待

**Comment by andandroidor** [comment]
OurTV电视版3.2.8版本隐藏技能：

援助任意金额：
可永久开启部分频道的回看功能
和
去除护眼提醒里面的二维码；

累计援助开发者超过99元：
3年内，
可开启遥控器上下键（或频道+-键）换台 
和 
可禁用护眼提醒。

不喜勿喷，感谢支持。
