### ISSUE TITLE
增加上下键换台功能

### ISSUE THREAD

**Issue by iviviviviviv** [andandroidor/ourtv#41]
现在不能直接换台需要点开列表选台，太麻烦
另外，1080p和关闭护眼是要赞赏才能解锁吗？

**Comment by andandroidor** [comment]
> 现在不能直接换台需要点开列表选台，太麻烦 另外，1080p和关闭护眼是要赞赏才能解锁吗？

上下键换台正在开发中

1080p只有部分频道有源，观看电视过程中完全免费

赞赏会有两个额外能力： 
- 提供部分频道的电视版回看功能  
- 只能去掉护眼的二维码 并不能关闭护眼提醒
感谢支持。

**Comment by andandroidor** [comment]
OurTV电视版3.2.8版本隐藏技能：

援助任意金额：
可永久开启部分频道的回看功能
和
去除护眼提醒里面的二维码；

累计援助开发者超过99元：
3年内，
可开启遥控器上下键（或频道+-键）换台 
和 
可禁用护眼提醒。

不喜勿喷，感谢支持。
