### ISSUE TITLE
央视频TV还有一个包：com.newtv.cboxtv

### ISSUE THREAD

**Issue by meteorain** [andandroidor/ourtv#47]
央视频在电视盒子上（电视果）和手机应用市场里还有一个官方包，包名是com.newtv.cboxtv，有些盒子（比如电视果）只接受安装这个包，能帮忙改下包名吗，我自己改没成功，APP不能启动。

**Comment by andandroidor** [comment]
包名恕不能更改。
您还可以开启电视的开发者模式，开启方式需要自行搜索。
然后电脑安装Android Command Tool，通过电脑命令行：
 adb connect ip地址 
的方式连接电视，再通过
adb install -r -f 
安装app。
