### ISSUE TITLE
遥控器按键可以调整一下吗？

### ISSUE THREAD

**Issue by psumycom** [andandroidor/ourtv#5]
习惯用确定键呼出换台选项卡，但现在按确定键就卡住1-2秒钟，按上下左右方向键才能出来换台菜单选项感觉很别扭，而且按1下返回键软件直接就退出了，希望能改成按2下返回键再退出，要不然很容易误碰到返回键导致APP退出，感谢老大！

**Comment by andandroidor** [comment]
收到，感谢反馈
