### ISSUE TITLE
电视应用黑屏

### ISSUE THREAD

**Issue by doyoudo** [andandroidor/ourtv#68]
我用了最新版的3.2.7还尝试了3.1.1都不行，只能听到声音，黑屏，请问这是什么原因导致的呢？

**Comment by Kakaxi-W** [comment]
我用着正常啊。安卓5.1。

**Comment by andandroidor** [comment]
> 我用了最新版的3.2.7还尝试了3.1.1都不行，只能听到声音，黑屏，请问这是什么原因导致的呢？

感谢反馈，什么系统版本呢？

**Comment by Kakaxi-W** [comment]
卸载，重启你的电视盒子，然后重新安装试一试？？？
