### ISSUE TITLE
小米电视，安装后，怎么无法上下换台呢？

### ISSUE THREAD

**Issue by xinpenghan** [andandroidor/ourtv#69]
遥控上下按键，怎么无法上下换台呢？

**Comment by andandroidor** [comment]
> 会有的

3年99元是否愿意？

**Comment by andandroidor** [comment]
OurTV电视版3.2.8版本隐藏技能：

援助任意金额：
可永久开启部分频道的回看功能
和
去除护眼提醒里面的二维码；

累计援助开发者超过99元：
3年内，
可开启遥控器上下键（或频道+-键）换台 
和 
可禁用护眼提醒。

不喜勿喷，感谢支持。
