### ISSUE TITLE
说明:2.蓝光清晰度部份频道不生效，会自动切换为高清(可不可以「会自动切换为超清」)

### ISSUE THREAD

**Issue by javadodobird** [andandroidor/ourtv#7]
说明:2.蓝光清晰度部份频道不生效，会自动切换为高清(可不可以「会自动切换为超清」)

**Comment by andandroidor** [comment]
> 说明:2.蓝光清晰度部份频道不生效，会自动切换为高清(可不可以「会自动切换为超清」)


因为不同清晰度对应的网络带宽不同，切换高清是为了降低带宽占用，减少卡顿，提升播放的成功率，超清会可能卡一点，默认情况可能得牺牲一下画质了，感谢理解
