### ISSUE TITLE
中国天气和陕西卫视。

### ISSUE THREAD

**Issue by xiaomodelvyou** [andandroidor/ourtv#71]
建议不要再保留中国天气和陕西卫视这两个频道了。根本就不正常。上个版本到现在从来就没有看到这两个频道正常过。85个频道正好了。可以删除两个。

**Comment by andandroidor** [comment]
为啥我这能看啊

**Comment by xiaomodelvyou** [comment]
> 为啥我这能看啊
都说过了，出一个央视加入cctv3。然后去掉扩展台的版本就够了。57个台正好，不用那么多台。

**Comment by xiaomodelvyou** [comment]
> 为啥我这能看啊

扩展台一会能看一会不能看的多闹心啊。
