### ISSUE TITLE
mumu模拟器上安装后，选台太费劲了 没等选 就列表自动关闭了，打开又要重新选一边

### ISSUE THREAD

**Issue by liuzheng110** [andandroidor/ourtv#74]
鼠标或者光标 再列表上能不能不要自动关闭，源基本都能用 非常棒，但是 卡酷，金鹰卡通这种源是不是可以加进来
还有能不能收藏台，主要是选台太费劲了

**Comment by andandroidor** [comment]
装电视上体验下吧 
场景不同体验不同 
模拟器建议安装手机版。
