### ISSUE TITLE
上下键换台99元，真有你的

### ISSUE THREAD

**Issue by iviviviviviv** [andandroidor/ourtv#77]
上下键换台99元，真有你的，想钱想疯了，等着接举报吧，祝平安

**Comment by andandroidor** [comment]
OurTV电视版3.2.8版本隐藏技能：

援助任意金额：
可永久开启部分频道的回看功能
和
去除护眼提醒里面的二维码；

累计援助开发者超过99元：
3年内，
可开启遥控器上下键（或频道+-键）换台
和
可禁用护眼提醒。

不喜勿喷，感谢支持。



看来你这狗眼看不见   不喜勿喷   4个字

**Comment by andandroidor** [comment]
![image](https://github.com/user-attachments/assets/c81c9e74-e6a0-4f6c-ad2d-8df1766d6809)
狗眼去看看  一年33 你都掏不起   去用50的吧 翻墙也是免费的吧
